language: node_js

node_js:
  - 8
  - node

install:
  - npm install

services:
  - postgresql

script:
  - npm test

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  
# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"